### ISSUE TITLE
Does it preform normally?

### ISSUE THREAD

**Issue by zydmu123** [andres-fr/face_segmentation_pytorch#1]
Below images are some of my test results for this code, I wonder whether it preforms normally, cause the result is so poor.

![图片2](https://user-images.githubusercontent.com/111970347/222035768-b5a5dfe6-8185-4ca2-b368-120daa469c51.png)

**Comment by andres-fr** [comment]
Hi, fair question. A couple of thoughts:
1. How did you normalize the images? What shape do they have? I believe around `500x500` is recommended, and [here](https://github.com/andres-fr/face_segmentation_pytorch/blob/65cad6e64130a3f079bfbfd9d78d5009af55647e/face_segmentation_pytorch/model.py#L107) is how I normalized them, based on the original code (see [here](https://github.com/YuvalNirkin/face_segmentation/blob/6d9fc81a32e396bcafae6ba61318a23427f6aa98/interfaces/python/face_seg.py#L9))
2. Often, the false positives in the heatmap disappear after thresholding, but yeah we still do see false negatives. Normalization may help.
 
The images I provide in the readme are a rather challenging subset (beards, glasses, different ethnicity and gender, not 500x500) and not cherry-picked, and from an open dataset that was likely not involved in training (I didn't check this). The images you provide seem less challenging, that's why I imagine normalization or shape may be an issue in your end. Let me know.

All I did was to transfer the weights and the architecture to PyTorch, but there could be some mistake in the process. I did not perform a quantitative evaluation, but contributions are welcome!

Hope this helps,  
Andres

**Comment by zydmu123** [comment]
@andres-fr Thanks for your answer. Now, I add the "input_img =input_img.resize((500, 500))" in the preprcocessing. The performance seems better, but there are still some obvious mistake like the border of the below images.
 
![图片1](https://user-images.githubusercontent.com/111970347/222429493-321235db-756e-4625-9dfe-766b6f17689a.png)

**Comment by andres-fr** [comment]
I'm glad that worked!

I've also observed this artifact, which I believe is a consequence of some hard-coded parameters in the architecture (i.e. pooling, upsampling and cropping). Check the original model architecture, defined in the [.prototext file](https://github.com/andres-fr/face_segmentation_pytorch/files/10871548/400x400prototext.txt), for details.



My guess is that, if you won't retrain the model, the best you can do is trying to resize the input images untill it disappears, pad the input with something like zeros/background value, or crop the output (see that the artifact seems to have a more or less fixed size). All trial-and-error.

Another alternative would be to extend this repository in order to integrate their [smaller 300x300 model](https://github.com/YuvalNirkin/face_segmentation/releases/tag/1.1), although I can't guarantee this would fix the issue. For the moment I don't contemplate this, but contributions are welcome.

I'm closing this issue since you've seem to have gotten as far as I did.  Cheers!  
Andres

**Comment by andres-fr** [comment]
I forgot to add, picking a higher threshold can also help of course!
